# Generated by Django 6.0.6 on 2026-07-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Заголовок")),
                (
                    "content",
                    models.CharField(max_length=150, verbose_name="Содержимое"),
                ),
                (
                    "preview",
                    models.ImageField(
                        upload_to="blog/images", verbose_name="Изображение"
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("publication_status", models.BooleanField(default=True)),
                ("number_of_views", models.IntegerField()),
            ],
            options={
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
                "ordering": ["title"],
            },
        ),
    ]
