# Generated by Django 6.0.6 on 2026-07-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogentry",
            name="number_of_views",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="blogentry",
            name="preview",
            field=models.ImageField(
                blank=True, upload_to="blog/images", verbose_name="Изображение"
            ),
        ),
    ]
