# Generated by Django 6.0.6 on 2026-06-30 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_name",
                    models.CharField(max_length=150, verbose_name="Наименование"),
                ),
                (
                    "description",
                    models.CharField(max_length=150, verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Наименование",
                "verbose_name_plural": "Наименования",
                "ordering": ["title_name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=150, verbose_name="Название"),
                ),
                (
                    "product_description",
                    models.CharField(max_length=150, verbose_name="Описание"),
                ),
                (
                    "picture",
                    models.ImageField(upload_to="photos/", verbose_name="Изображение"),
                ),
                (
                    "purchase_price",
                    models.IntegerField(null=True, verbose_name="Цена за покупку"),
                ),
                ("created_ad", models.DateTimeField(auto_now_add=True)),
                ("updated_ad", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Название",
                "verbose_name_plural": "Названия",
                "ordering": ["product_name"],
            },
        ),
    ]
