# Generated by Django 6.0.6 on 2026-08-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_category_options_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="picture",
            field=models.ImageField(
                blank=True, upload_to="catalog/picture", verbose_name="Изображение"
            ),
        ),
    ]
