# Generated by Django 6.0.6 on 2026-08-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status_publications",
            field=models.CharField(
                choices=[
                    ("published", "опубликован"),
                    ("not_published", "не опубликован"),
                ],
                default="not_published",
                max_length=30,
                verbose_name="Публикация",
            ),
        ),
    ]
