# Generated by Django 6.0.6 on 2026-08-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_status_publications"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["title_name"],
                "permissions": [("can_unpublish_product", "Can unpublish product")],
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
    ]
